### PR TITLE
Provide grgsm_livemon_headless for running from scripts.

### PR DESCRIPTION
**Pull request by petterreinholdtsen**
Implements fix for https://github.com/ptrkrysik/gr-gsm/issues/312 .

### CODE REVIEW

**Comment by ptrkrysik** [comment]
Hi @petterreinholdtsen ,

What is the purpose of  apps/grgsm_livemon_headless.patch file added in the apps directory by commit ff50103ff582aa?

**Comment by petterreinholdtsen** [comment]
It is to document the changes done to grgsm_livemon.grc to create grgsm_livemon_headless.grc.  The idea is to provide the recipe to update grgsm_livemon_headless.grc when grgsm_livemon.grc is modified.

**Comment by ptrkrysik** [comment]
It can only work if the changes are done manually. But for this purpose
the patch is not much readable. In my opinion it is better to add some
comment in the Readme from apps directory that grgsm_livemon_headless
was created from grgsm_livemon by switching Generate Options to No GUI,
removing QT Gui Frequency Sink, removing sliders and replacing g_slider
variable references with gain, fc_slider with fc and ppm_slider with ppm.

**Comment by petterreinholdtsen** [comment]
[Piotr Krysik]
> It can only work if the changes are done manually. But for this
> purpose the patch is not much readable. In my opinion it is better to
> add some comment in the Readme from apps directory that
> grgsm_livemon_headless was created from grgsm_livemon by switching
> Generate Options to No GUI, removing QT Gui Frequency Sink, removing
> sliders and replacing g_slider variable references with gain,
> fc_slider with fc and ppm_slider with ppm.

OK, I'll try to do it this way and remove the patch. :)

But the headless grc file really was not created that way.  It was
created by me hand-editing the XML in the way documented in the
patch. :)

Anyway, what about renaming g_slider to gain_slider, to allow the
original XML to be edited using 'sed -i s/_slider//g' before removing
all the Qt block references?  It would make the variable name more
consistent with the others, which are all named <parameter>_slider. :)

-- 
Happy hacking
Petter Reinholdtsen

**Comment by ptrkrysik** [comment]
W dniu 28.08.2017 o 20:25, petterreinholdtsen pisze:
> Anyway, what about renaming g_slider to gain_slider, to allow the
> original XML to be edited using 'sed -i s/_slider//g' before removing
> all the Qt block references? It would make the variable name more
> consistent with the others, which are all named <parameter>_slider. :)
> 

Definitely good idea.

**Pull request merged**
