### PR TITLE
TCH/F decoder implementation

### PR DESCRIPTION
**Pull request by romankh**
Hi, 

here is a working implementation of TCH/F decoder.
It's an integration of the OpenBTS code used for decoding TCH in airprobe. 
Both GSM-FR and GSM-EFR are supported, but only GSM-FR is tested. 
FACCH decoding also looks reasonable, the output corresponds with my expectations.

I concentrated on getting the feature working, however there is space for optimizations.

### CODE REVIEW

**Comment by akibsayyed** [comment]
Please share GRC too I will test and will give results

**Comment by ptrkrysik** [comment]
Great! I will test it today evening and if it's ok I will add everything to the main repository.

**Comment by ptrkrysik** [comment]
Hi @romankh ,

I'm not able to decode my test data yet. I added is gr-gsm/examples/airprobe_tchf.grc file that works on conversation.cfile that can be downloaded here: https://svn.berlin.ccc.de/projects/airprobe/attachment/wiki/DeModulation/piotr_downlink_first.tar.bz2

Are you able to change the airprobe_tchf.grc so it can decode TCH/F messages? I can decode SACCH messages with it but not TCH/F.

**Comment by romankh** [comment]
Your flowgraph is fine, same result here. I must admit that I have only tested with an unencrypted capture. Will try to find the problem.

**Comment by romankh** [comment]
It's a bit strange.
I also found your second test capture there at https://svn.berlin.ccc.de/projects/airprobe/attachment/wiki/DeModulation/piotr_downlink_second.tar.bz2, and played around with it.

Now the strange part: sometimes the decoder outputs SACCH and FACCH on the timeslot, but most of the time I get only SACCH as with the first capture. 

Is it possible that the decimation of the capture plays a role ? 
Do you have a capture recorded with gr-gsm, that I could use here ?
All providers here in my area have hopping channels for traffic channels, I didnt find a cell without so far, so that I can get an encrypted non-hopping TCH/F channel capture.

**Comment by ptrkrysik** [comment]
> It's a bit strange.
> I also found your second test capture there at
> https://svn.berlin.ccc.de/projects/airprobe/attachment/wiki/DeModulation/piotr_downlink_second.tar.bz2,
> and played around with it.
> 
> Now the strange part: sometimes the decoder outputs SACCH and FACCH on
> the timeslot, but most of the time I get only SACCH as with the first
> capture.

It is possible that there are false positives after parity check.

> Is it possible that the decimation of the capture plays a role ?
> Do you have a capture recorded with gr-gsm, that I could use here ?
> All providers here in my area have hopping channels for traffic
> channels, I didnt find a cell without so far, so that I can get an
> encrypted non-hopping TCH/F channel capture.
> 

The decimation isn't a culprit here as whole timeslot 0 and SACCH from
timeslot 7 are decoded corretly. The decimation was a parameter of USRP
btw. - the sampling frequency was 64e6/decimation.

I was able to decode that conversation with airprobe. Decryption from
gr-gsm was also tested and works with SACCH from the same capture.

Maybe there is some bug in the demapping that appears only for some
timeslots?

**Comment by akibsayyed** [comment]
I can help  you  with non hopping capture

**Comment by ptrkrysik** [comment]
@akibsayyed

Are you able to provide non-encrypted and encrypted (with Kc key)
captures containing voice data?

**Comment by akibsayyed** [comment]
Yes I can

**Comment by akibsayyed** [comment]
But non hopping

**Comment by romankh** [comment]
> It is possible that there are false positives after parity check.

Yes, could be. However it doesn't look so bad, I have a Connect Acknowledge, Release and Channel Release message in the order I would expect.

> The decimation isn't a culprit here as whole timeslot 0 and SACCH from
timeslot 7 are decoded corretly. The decimation was a parameter of USRP
btw. - the sampling frequency was 64e6/decimation.

A time ago I tried to process the capture file of srlab's airprobe tutorial (vf_call6_a725_d174_g5_Kc1EF00BAB3BAC7002.cfile.gz), which was captured using a USRP2. 
I tried using the sample freq 100e6/174, but I wasn't able to get it running. 

Maybe you can provide me the right settings for that file ? I can upload it, if you don't have it. 

> Maybe there is some bug in the demapping that appears only for some
timeslots?

Yes, I considered that too. More testdata would make finding the issue easier.

**Comment by romankh** [comment]
@akibsayyed, non-hopping is great. Can you upload it and post a link or something ?

**Comment by akibsayyed** [comment]
I will capture them tommrow and will upload them

**Comment by ptrkrysik** [comment]
Hi guys,

Congratulations to you @romankh. With your decoder it is possible to get speech from vf_call6_a725_d174_g5_Kc1EF00BAB3BAC7002.cfile.gz file (it is available on google docs). This is the flowgraph that does that:
https://app.box.com/s/rnrrdip7bwjgtfg4kkf2ik1i8kajjesq

The decoder works very well on this file, I wonder why it doesn't work on my old test data but it isn't the most important matter. 

I will add the decoder and demapper to the main branch as as they are clearly functional.

**Comment by romankh** [comment]
Thanks a lot, that's good news.

**Comment by akibsayyed** [comment]
here is EFR Codec speech file

http://matrixshell.com/cfile/EFR_Full%20_rate/EFR_Full_rate.cfile


http://matrixshell.com/cfile/EFR_Full%20_rate/efr_abis.pcapng

abis pcap capture

http://matrixshell.com/cfile/EFR_Full%20_rate/efr_s2.pcapng

cellphone side capture

On Fri, May 22, 2015 at 12:09 AM, romankh <notifications@github.com> wrote:

> Thanks a lot, that's good news.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ptrkrysik/gr-gsm/pull/53#issuecomment-104382935>.
>



-- 
Akib Sayyed
Matrix-Shell
akibsayyed@gmail.com
akibsayyed@matrixshell.com
Mob:- +91-966-514-2243

**Comment by romankh** [comment]
Thanks @akibsayyed, 
can you provide sample rate and channel ?

**Comment by ptrkrysik** [comment]
From what I figured out the sample rate is 1e6. You also need to add dc blocker block after the file source as the signal contains high DC offset. I don't know the channel yet, but I just set carrier frequency to 937e6 and it works.

**Comment by romankh** [comment]
Thanks you, got the C0.
Unfortunately, TCH is not working again. Only SACCH. Did it work for you ?

**Comment by ptrkrysik** [comment]
TCH doesn't work for me either. Maybe there is something with the
demapper in this particular situation or with interconnection between it
and the decoder. Do you have some idea?

**Comment by romankh** [comment]
I will check the demapper and the de-interleaving tomorrow, this the best guess I have for now.

**Comment by akibsayyed** [comment]
Guys sample rate it 1e6 and freq is PCs 1900 514

**Comment by romankh** [comment]
Ok, I found that bug in the demapper's check for consecutive frames.
Now I get FACCH for all the testfiles.

Speech decoding works for GSM-FR now, but unfortunately not for EFR. 
Both piotr_downlink_second and akibsayyed's capture have the speech file output puzzled.

I will create the pullrequest soon, so we get the bug out of the main repo. 

Will investigate the EFR problem

**Comment by romankh** [comment]
I forgot the magic bytes for GSM-EFR. 
Tested it with both captures, works now.

**Comment by akibsayyed** [comment]
I have working efr codec example I tested it with these samples

**Comment by romankh** [comment]
Thanks, should be working now. 
You can test it with the modifications from pull request #54

**Comment by romankh** [comment]
@akibsayyed, does your setup also support GSM-AMR ? 

If so, it would be great if you can provide some captures with AMR 10.2 and lower, on FR channel. 
I'd like to add support for those encodings too, test data would be helpful.

**Comment by akibsayyed** [comment]
Yes I have support for same will upload them and will let u know

**Comment by ptrkrysik** [comment]
Great to hear that.

I will add the fix to the repo this evening. @romankh - consider also
fixing the "author" section in tch decoder and demapper source files to
yourself ;).

**Pull request merged**
