### PR TITLE
Correct CRC errors

### PR DESCRIPTION
**Pull request by velichkov**
- Try to correct CRC errors
  In _xcch_decode_cB when the osmo_crc64gen_check_bits fails use
  FC_check_crc to try to correct errors.
  Revert fire_crc.[hc] as of 8038b2e
- Add tests using bursts from test_data/sms_multirtl_uplink_tail.cfile
- Add LOCAL_OSMOCOM cmake option 
  When set the gr-gsm will be compiled and linked with the local copies of
  the osmocom libraries.
- In Travis run tests with CTEST_OUTPUT_ON_FAILURE=1
  This way there is an output when a test fails which makes debugging failures a lot easier.

### CODE REVIEW

**Comment by ptrkrysik** [comment]
Hi @velichkov, regarding the decoding errors - is libosmocoding missing something in this regard? If yes I would rather correct their implementation than introduce the fire_crc.* files that have unknown license.

**Comment by velichkov** [comment]
Hi Piotr,

I also though about contributing to osmocom but the thing is I'm not sure if they are missing something. They have some error correction and have [a test for it](
https://github.com/osmocom/libosmocore/blob/520ebc17d9351ccd1a053eeb11c769649e4d1fc1/tests/coding/coding_test.c#L89-L97) but as my test shows their error correction is not as good as the one in fire_crc.c.

With the current development branch (9b5702f36f3d3669d4c82a7f3aab0cd342fc18e5) I'm not able to decode the uplink SMS (packet 15) using your example scripts as described in https://ptrkrysik.github.io/, so I did `git bisect` and found out that the "regression" starts when the libosmocore decoding was integrated, and then I narrowed it down the the fire_crc.

I don't understand the code in fire_crc.* at all and was not able to find where it comes from nor a description of the algorithm. I agree that it is not good to add code with unknown license but this is also valid for libosmocore. Do you have any clue from where this code was taken or do any information about the algorithm? Maybe we could re-implement it if we know what it does.

**Comment by ptrkrysik** [comment]
I cherry-picked 52cd539aa445a541014db72a1d2c8732361699ab and 4a8a46d649e96a9a34e8879d729eb9572346caa1 commits to the development branch.

**Comment by velichkov** [comment]
I found a description of the algorithm in "3GPP TS 45.003 version 14.2.0 Release 14" - "4.1.2
Block code" and now I believe I'm starting to understand the code in `fire_crc.c`.

**Comment by ptrkrysik** [comment]
From what I see in the libosmocoding - it doesn't try to fix the errors detected with use of the fire code.

**Comment by axilirator** [comment]
Please also note #417. The Receiver block should provide soft-bits (-127...127) as expected by libosmocoding, but at the moment we have hard-bits (0 or 1) only. This would allow to improve decoding results.

**Pull request closed without merging**
