### PR TITLE
App for RTL-SDR single channel capture

### PR DESCRIPTION
**Pull request by romankh**
Hi @ptrkrysik, 

as discussed in the mailing list ( https://groups.google.com/forum/#!topic/gr-gsm/6yDRRGNXD4g), here comes the first app, no giant leap:

* added support for arfcn calculation
* app itself takes either frequency or arfcn as param
* either saves capture to cfile or burst file, or both
* Option -v prints the captured bursts to provide user with feedback that there are bursts that are captured

### CODE REVIEW

**Comment by ptrkrysik** [comment]
Hi Roman,

Was this intentional that this block has GUI? It shouldn't be required in this case as this program is intended to be invoked from commandline. Getting rid of GUI will simplify python code as well.

**Comment by romankh** [comment]
Hi Piotr, 

yes, it was intentional. First I wanted to do it without GUI, but than I decided to keep it. 
However the capturing app is gonna be the only one with GUI, it doesn't make sense. 
I also thought about making the GUI optional, can still do it easily, if you want.

**Comment by romankh** [comment]
After thinking about it again, I will remove the GUI

**Comment by ptrkrysik** [comment]
W dniu 24.08.2015 o 08:53, Roman Khassraf pisze:
> After thinking about it again, I will remove the GUI
> 

Hi Roman,

Ok, so I will wait with merging.

-- 
Best Regards,
Piotr Krysik

**Comment by romankh** [comment]
Hi Piotr, 

I removed the GUI now, and also added methods for setting / getting arfcn in the class.

**Pull request merged**
