### PR TITLE
Fix operator precedence in comparisons

### PR DESCRIPTION
**Pull request by stiabhan**
Hi Piotr

Can you please merge this branch - the operator precedence of '==' is higher than for '|' so the existing code is in error.

Kind regards

Steve Glass

### CODE REVIEW

**Comment by ptrkrysik** [comment]
@stiabhan, thanks for the correction. I'll first merge your pull request with development branch, then with master.

**Comment by stiabhan** [comment]
Hi Piotr

Just a quick follow up concerning the wideband input adapter…

So I only managed to get the clock offset corrector working with the narrowband input. There is *definitely* a regression in the wideband input adapter. The change in the clock offet corrector is the cause of the problem. I've temporarily modified the wideband block to remove the clock offset corrector and it works just fine. When present the output of the clock offset corrector is “weird” and messed up - screwing up the following stages of the block.

Apols for the private email - I can probably muddle my way through the signal processing and the python code is trivial but I thought to contact you just in case you have a quick solution; otherwise I’ll send a pull request when I’ve made the changes.

ATB

Steve

**Comment by stiabhan** [comment]
The problem is discovered - frequency resampling is occurring in the clock offset control!

I’ll prep a change tomorrow :)

**Comment by stiabhan** [comment]
Sorry, the problem is the resampling in the clock offset *control*!

**Comment by ptrkrysik** [comment]
W dniu 11.03.2017 o 13:01, smdg pisze:
> Hi Piotr
> 
> Just a quick follow up concerning the wideband input adapter…
> 
> So I only managed to get the clock offset corrector working with the
> narrowband input. There is *definitely* a regression in the wideband
> input adapter. The change in the clock offet corrector is the cause of
> the problem. I've temporarily modified the wideband block to remove the
> clock offset corrector and it works just fine. When present the output
> of the clock offset corrector is “weird” and messed up - screwing up the
> following stages of the block.
> 
> Apols for the private email - I can probably muddle my way through the
> signal processing and the python code is trivial but I thought to
> contact you just in case you have a quick solution; otherwise I’ll send
> a pull request when I’ve made the changes.
> 
> ATB
> 
Hi @smdg. I think I know what is happening. I've changed names of
message inputs/outputs used for passing frequency correction messages.
For sure I forgot to change it in the gsm_wideband_input. The reason I
forgot is that it isn't used in existing apps so I didn't see the any
crash (and there is no unit test for it, but this is more general
problem of gr-gsm components).

But this might not be the end - I messed with frequency correction in
July 2016. I corrected one big problem with it, but I might have
introduced some other bug.

Big thank you for pointing this. Are you provide some test that presents
the problem? This will considerably speed up correcting this.

**Comment by stiabhan** [comment]
Hi Piotr,

Thanks for the reply. I sent through a pull request which is working for me but you should read the attached notes - I am pretty happy but I think it can be improved :)

ATB

Steve

**Comment by ptrkrysik** [comment]
W dniu 14.03.2017 o 11:54, smdg pisze:
> Hi Piotr,
> 
> Thanks for the reply. I sent through a pull request which is working for
> me but you should read the attached notes - I am pretty happy but I
> think it can be improved :)
> 
> ATB
> 
> Steve
> 

I've just noticed your pull request (I have some backlog of gr-gsm
related messages, and I'm trying to answer them starting from the oldest
;) ). Thanks for your work. I'll try to look into this.

Piotr

**Comment by stiabhan** [comment]
Thanks Piotr!

In the longer term I’m sure that things can be done the same as in the channelized helper. I’ll have a think about this and see if I can prepare some further changes.

ATB

Steve

**Pull request merged**
