### PR TITLE
Check the gsm0503_xcch_decode return value

### PR DESCRIPTION
**Pull request by velichkov**
- Discard the message when gsm0503_xcch_decode returns -1
- Add automated decrypt test

See https://groups.google.com/d/msg/gr-gsm/9nOkIdrGOck/qTZh47McCQAJ

### CODE REVIEW

**Comment by velichkov** [comment]
Hi @pkrysik,

The new test failed in `tests/dockerfiles/Debian_testing_package.docker` because in this container `gr-gsm` is installed from the `apt` repository and because of this it is the old version. I believe it will be good to not test with this container in travis.

**Comment by pkrysik** [comment]
Hi Vasil,

I agree that it might not make sense to test the package installation
each time there is something new in the repository and I can disable
this test. Can you paste a link showing failed travis-ci test?

**Comment by pkrysik** [comment]
Ok, I've got that test

**Comment by velichkov** [comment]
>  Can you paste a link showing failed travis-ci test?

For the record [here](https://travis-ci.org/ptrkrysik/gr-gsm/jobs/358665970#L3726) is the log

>  I can disable this test.

I just pushed a commit that remove this container from `.travis.yml` only.

**Comment by velichkov** [comment]
Hi @pkrysik,

While playing with `mutlirtl_rx_to_cfile_2chan.py` example I noticed that the SMS is no longer decoded with the newest versions and it turns out that in `gsm0503_xcch_decode` there is no CRC error correction similar to the one in `FC_check_crc` that was used before the libosmocore migration.

In a new branch in my repo I added a test 1dbdef8ff40f2350fa7296ea94d9fc2da2acb863 that successfully executes on older versions and in e689ff5531ee107204fd3d68d5963ef2b25f224b I've reverted the fire_crc.[hc] in order to use the `FC_check_crc` from within osmocom code. Let me know if you want to include these changes in this PR

**Pull request merged**
