### PR TITLE
2 bug fixes and subslot assignment in universal ctrl channel demapper

### PR DESCRIPTION
**Pull request by romankh**
Hi @ptrkrysik, 

here are 
- a fix for issue #33 
- a fix for a incorrect condition, which induce that first and last frame were not assigned a channel type 
- an improvement: Added the assignment of subslots for given channels, such that subslots can be used in filtering captures in e.g. wireshark. This makes tracking messages easier.

### CODE REVIEW

**Comment by ptrkrysik** [comment]
Hi @romankh,

I've added all your commits. Many thanks for the bugfixes and addition of new features. I have some questions regarding the addition of sub_type.

**Comment by romankh** [comment]
The intention is to provide the information about the sub-channel of some control channel, primarily SDCCH, SACCH & co. 

I am not sure why in gsmtap they denamed it sub-slot, however i have seen the implemented behaviour in another tool using gsmtap, and i found it very useful. Maybe Airprobe, it is mentioned also in BogdanDia's Airprobe-Hopping paper, see http://yo3iiu.ro/blog/wp-content/uploads/2012/04/Evaluating_GSM_hopping_V1.2.pdf)

For example, in wireshark i found an immediate assignment, where a SDCCH/8 + SACCH/C8 is assigned to some MS. The assignment also denotes the subchannel 7.

immediate-assignment

By writing the subchannel into the gsmtap header, we now can simply filter for the right sub_slot, such wireshark displays only the messages in the subchannel assigned to the MS. To follow the assigned subchannel in the screenshot, i would use the filter expression "gsmtap.ts == 1 && gsmtap.sub_slot == 7".

The subchannels are described in GSM 05.02 (http://www.etsi.org/deliver/etsi_gts/05/0502/05.00.00_60/gsmts_0502v050000p.pdf), Section 7 Table 4 gives a nice overview for SDCCH/8 and SACCH/C8

**Comment by romankh** [comment]
Regarding what is written to the header to sub_slot: 
In the constructor, i keep track of how often a distinct type of channel is assigned, and prepare the array d_subslots which just contains the subchannel for the burst with the corresponding fnr_mod51. 

E.g., for an SDCCH/8, the first SDCCH message is assigned header->sub_slot = 0, the second = 1, and so on. I am using an array with length 102 to be able to consider ACCH messages as well, where for example in case of SACCH/C8, the 4 SACCH in the first 51-multiframe have subchannel 0 - 3, and the 4 SACCH in the second 51-multiframe have subchannel 4 - 7

**Comment by ptrkrysik** [comment]
This is very good idea. Even if the original idea was (I'm not sure of
it) to put there some number of sub-timeslot, for messages it is much
more usable to be able to tell to which subchannel given message
belongs. Especially that two halves of bursts are used separately only
for traffic channels.

**Comment by ptrkrysik** [comment]
Currently the method of assigning of subchannels is implicit. Maybe it
will be better to assign them explicitly in parameters.

On the side note: this block can be more general and support more
control channels mapping than currently (now it supports mainly 51
multiframes) so it will require some redesign.

**Pull request merged**
