### PR TITLE
Implementation of TCH/F demapper block. See issue #38

### PR DESCRIPTION
**Pull request by romankh**
Hi @ptrkrysik, 

this is my basic implemenation of the TCH/F demapper block, as we discussed in Issue #38.

### CODE REVIEW

**Comment by ptrkrysik** [comment]
I've briefly tested the code. I'm able to get some decoded messages so it's very promising. I'm not sure if they are correctly decoded as Wireshark don't analyse them correctly (maybe it's matter of my test data or settings from GSMTAP header).

The demapping of TCH and FACCH needs probably to be corrected. The TCH and FACCH use block diagonal interleaving. If you look into 3GPP 05.02 (Section 7 Table 1), FACCH/F is sent across 8 consecutive frames (modulo 26). This is because block interleaving is applied. The block diagonal interleaving is described in 05.03 specification, another description is for example here ( Section 1.5.4.3):
http://etutorials.org/Mobile+devices/gprs+mobile+internet/Chapter+1+Introduction+to+the+GSM+System/Radio+Interface/

Keep the good work!

**Comment by romankh** [comment]
Yes, you are totally right, i missed that regarding the TCH and FACCH. 
Will fix that the next days.

**Comment by ptrkrysik** [comment]
I've pushed this pull request to romankh-tchf branch (https://github.com/ptrkrysik/gr-gsm/commits/romankh-tchf).

**Comment by romankh** [comment]
Ok, thank you

**Comment by ptrkrysik** [comment]
My initial idea was that logical channels demapper should just filter and group bursts. I see now that interface based on bursts might not be optimal in case of TCH/F and FACCH channels - so one solution would be to change interface. Another option is that FACCH would require a little different decoder - that does block diagonal de-interleaving.

**Pull request closed without merging**
