### PR TITLE
Created standalone GSM channelizer app for splitting wideband cfiles

### PR DESCRIPTION
**Pull request by rpp0**
I've created an app that allows us to channelize wideband cfiles into multiple cfiles per channel. This is a required preprocessing step for decoding hopping channels at the moment. In the future, we could integrate this functionality in a block for realtime channelization (see https://github.com/ptrkrysik/gr-gsm/issues/105), but I need to do some tests in order to see whether this is feasible in terms of CPU load.

### CODE REVIEW

**Comment by ptrkrysik** [comment]
Regarding realtime channelization on CPU - this might not be possible. However it might be helpful to have working polyphase gsm channelizer working on CPU before making GPU or FPGA version (currently with help Ettus RFNoC it is not as hard as it used to be to implement something in USRP's FPGA).

**Comment by ptrkrysik** [comment]
@rpp0 - can you add short information about the application on the project's wiki?
https://github.com/ptrkrysik/gr-gsm/wiki/Usage

**Comment by henricazottes** [comment]
Hi, 
I have one remark and one question about hopping channel decoding.
First the remark: the sample rate in the wiki for grgsm_channelize (20M) is different from the rate given in the help (-h) of the command (2M).
And so comes my question: wich one is correct ? :p

Still, even with this information I don't clearly see how to get my speech.au.gsm with the resulting files... Do you think you will add more information about it ?

Thanks :)

**Comment by ptrkrysik** [comment]
W dniu 29.04.2016 o 18:45, Henri Cazottes pisze:
> Hi,
> I have one remark and one question about hopping channel decoding.
> First the remark: the sample rate in the wiki for grgsm_channelize (20M)
> is different from the rate given in the help (-h) of the command (2M).
> And so comes my question: wich one is correct ? :p
> 
> Still, even with this information I don't clearly see how to get my
> speech.au.gsm with the resulting files... Do you think you will add more
> information about it ?
> 
> Thanks :)
> 
Hi,

The help info is correct.

Regarding getting speech out of hopping data - I haven't succeed to do
this yet. I'm able to get control frames but voice for some unknown
reason is not decoded correctly.


-- 
Best Regards,
Piotr Krysik

**Comment by ptrkrysik** [comment]
W dniu 29.04.2016 o 18:45, Henri Cazottes pisze:
> Hi,
> I have one remark and one question about hopping channel decoding.
> First the remark: the sample rate in the wiki for grgsm_channelize (20M)
> is different from the rate given in the help (-h) of the command (2M).
> And so comes my question: wich one is correct ? :p
> 
> Still, even with this information I don't clearly see how to get my
> speech.au.gsm with the resulting files... Do you think you will add more
> information about it ?
> 
> Thanks :)
> 
Hi,

The help info is correct.

Regarding getting speech out of hopping data - I haven't succeed to do
this yet. I'm able to get control frames but voice for some unknown
reason is not decoded correctly.

For further discussion regarding hopping - lets continue it on the
mailing-list.

-- 
Best Regards,
Piotr Krysik

**Pull request merged**
